language: csharp
solution: WikiClientLibrary.sln

branches:
  only:
  - master

env:
  global:
  - secure: "RPlA+JVww+AXPRO+f3u7FS+cgqxm+nJwCJUnRfSdBUyejzw/WtjBYWcdjbjK0UkgM8+/mZoDPapXOAYhsoVtJNTaDNz/3ec6k8geWiWKrOV+R0xQaLvuwZ7Myvvw9njbPpNvLvfHEqghDv+UlG7+Yz9/lF3RL/MqeIDjjloCLCyN85T0ShD4bk8vBAeytpwv0VLvfWXEAMNglwuMgxBwpVz7qV9ayTh5Fi2r7Z976ZqJLhOS0qw8L2MwJ91fHuF8xWc0RKRqv4aSNlGwy9nLYtjrIGhmrjcl62Kf5wHcDTaZwZz0YDDRYZP8iUzppUe2s5hx3QMfknZgT7VH/ShvvSJ4OHKSe9hp/VQklAgUzo1lJxG22eirpJZCuOTi2G5omuKaevV4AUmYdVixfVi1o7nW2dK0lbfDMBiINWrmxbWWvQCzvJ06lSEfFkaibC3n9CpnPXupxezd7BFUFN3y6di0WNTdiewsA7VciWLVBAoesqA6x/27pBs9Que2hL5wliecVPN3/FfJDakK/ihQmYEj5wT3vXPdzGpG6p7IdSshHRKZlAqTSAMKPe43aVqxxK9MC1Jua5qwrH3eEIjmZ8qukGeu5e1jtF6cJBV0kTv4i5UBSnWiK6Knmun7NIxy59qrQMlHCAIqljJJDTtHJqvvKNhJpRsdr3uRv8t3crI="

matrix:
  include:
    - os: linux
      dist: xenial
      mono: none
      # dotnet: 2.2.108
      dotnet: none
      env:
        - DOTNET_CLI_TELEMETRY_OPTOUT=1
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
install:
  - curl -SL -o dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-linux-x64.tar.gz
  - sudo mkdir -p /usr/share/dotnet
  - sudo tar -zxf dotnet.tar.gz -C /usr/share/dotnet
  - sudo ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
  - dotnet --info
  - pwsh -f ./WikiClientLibrary.Commons/CI/Install.ps1
script:
  - pwsh -f ./WikiClientLibrary.Commons/CI/Build.ps1
  - pwsh -f ./WikiClientLibrary.Commons/CI/Test.ps1
