language: csharp
solution: WikiClientLibrary.sln

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: xenial
      mono: none
      dotnet: 2.2.401
      env:
        - DOTNET_CLI_TELEMETRY_OPTOUT=1
        - WCL_IS_CI_BUILD=1
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
install:
  - sudo pwsh -f ./WikiClientLibrary.Commons/CI/Install.ps1
script:
  - pwsh -f ./WikiClientLibrary.Commons/CI/Build.ps1
  - pwsh -f ./WikiClientLibrary.Commons/CI/Test.ps1
