language: csharp
solution: WikiClientLibrary.sln

matrix:
  include:
    - mono: none
      dotnet: 2.2.108
install:
  - nuget restore WikiClientLibrary.sln
script:
  - msbuild /p:Configuration=Release WikiClientLibrary.sln
