language: csharp
solution: WikiClientLibrary.sln

matrix:
  include:
    - os: linux
      dist: xenial
      mono: none
      # dotnet: 2.2.108
      dotnet: none
      env:
        - DOTNET_CLI_TELEMETRY_OPTOUT=1
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
install:
  - curl -SL -o dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-linux-x64.tar.gz
  - sudo mkdir -p /usr/share/dotnet
  - sudo tar -zxf dotnet.tar.gz -C /usr/share/dotnet
  - sudo ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
  - dotnet --info
  - pwsh -f ./WikiClientLibrary.Commons/CI/Install.ps1
script:
  - pwsh -f ./WikiClientLibrary.Commons/CI/Build.ps1
  - pwsh -f ./WikiClientLibrary.Commons/CI/Test.ps1
