name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '*.txt'
  schedule:
    - cron: "7 0 * * MON"

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      WCL_IS_CI_BUILD: 1
      BUILD_SECRET_KEY: "${{ secrets.BUILD_SECRET }}"
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.0.100'
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build
        shell: pwsh
        run: ./WikiClientLibrary.Commons/CI/Build.ps1
      - name: Test
        shell: pwsh
        run: ./WikiClientLibrary.Commons/CI/Test.ps1
      - name: Cleanup
        shell: pwsh
        run: './WikiClientLibrary.Commons/CI/BuildSecret.ps1 -Clear'
