name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '*.txt'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '*.txt'
  schedule:
    - cron: "7 0 * * MON"
    - cron: "10 6 * * WED"
    - cron: "30 12 * * FRI"

jobs:
  build_linux:
    name: Linux Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      WCL_IS_CI_BUILD: 1
      BUILD_SECRET_KEY: "${{ secrets.BUILD_SECRET }}"
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            6.0.x
            8.0.x
          include-prerelease: true
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: PrepEnv
        shell: pwsh
        run: ./WikiClientLibrary.Commons/CI/PrepEnv.ps1
      - name: Build
        shell: pwsh
        run: ./WikiClientLibrary.Commons/CI/Build.ps1
      - name: CollectArtifacts
        shell: pwsh
        run: './WikiClientLibrary.Commons/CI/CollectArtifacts -Configuration Release'
      - uses: actions/upload-artifact@master
        with:
          name: BuildArtifacts-Linux-Release
          path: ./CollectedArtifacts
      - name: Test
        shell: pwsh
        run: ./WikiClientLibrary.Commons/CI/Test.ps1
  build_windows:
    if: success()
    name: Windows Build & Test
    runs-on: windows-latest
    timeout-minutes: 30
    strategy:
      matrix:
        config: ["Debug", "Release"]
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      WCL_IS_CI_BUILD: 1
      BUILD_SECRET_KEY: "${{ secrets.BUILD_SECRET }}"
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            6.0.x
            7.0.x
          include-prerelease: true
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: PrepEnv
        shell: pwsh
        run: './WikiClientLibrary.Commons/CI/PrepEnv.ps1'
      - name: Build
        shell: pwsh
        run: './WikiClientLibrary.Commons/CI/Build.ps1 -Configuration ${{ matrix.config }}'
      - name: CollectArtifacts
        shell: pwsh
        run: './WikiClientLibrary.Commons/CI/CollectArtifacts -Configuration ${{ matrix.config }}'
      - uses: actions/upload-artifact@master
        with:
          name: BuildArtifacts-Windows-${{ matrix.config }}
          path: ./CollectedArtifacts
      - name: Test
        shell: pwsh
        run: './WikiClientLibrary.Commons/CI/Test.ps1 -Configuration ${{ matrix.config }}'
