name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '*.txt'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '*.txt'
  schedule:
    - cron: "7 0 * * MON"

jobs:
  build_linux:
    name: Linux Build & Test
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      WCL_IS_CI_BUILD: 1
      BUILD_SECRET_KEY: "${{ secrets.BUILD_SECRET }}"
    steps:
      # Need to wait for https://github.com/actions/setup-dotnet/issues/25 to be resolved.
      # - uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: '3.0.100'
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: PrepEnv
        shell: pwsh
        run: ./WikiClientLibrary.Commons/CI/PrepEnv.ps1
      - name: Build
        shell: pwsh
        run: ./WikiClientLibrary.Commons/CI/Build.ps1
      - name: Test
        shell: pwsh
        run: ./WikiClientLibrary.Commons/CI/Test.ps1
      - name: CollectArtifacts
        shell: pwsh
        run: './WikiClientLibrary.Commons/CI/CollectArtifacts -Configuration Release'
      - uses: actions/upload-artifact@master
        with:
          name: BuildArtifacts-CIRelease
          path: ./CollectedArtifacts
  build_windows:
    if: success()
    name: Windows Build
    runs-on: windows-latest
    strategy:
      matrix:
        config: ["Debug", "Release"]
      fail-fast: true
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      WCL_IS_CI_BUILD: 1
      BUILD_SECRET_KEY: "${{ secrets.BUILD_SECRET }}"
    steps:
      # Need to wait for https://github.com/actions/setup-dotnet/issues/25 to be resolved.
      # - uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: '3.0.100'
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: PrepEnv
        shell: pwsh
        run: './WikiClientLibrary.Commons/CI/PrepEnv.ps1'
      - name: Build
        shell: pwsh
        run: './WikiClientLibrary.Commons/CI/Build.ps1 -Configuration ${{ matrix.config }}'
      - name: Test
        shell: pwsh
        run: './WikiClientLibrary.Commons/CI/Test.ps1 -Configuration ${{ matrix.config }}'
      - name: CollectArtifacts
        shell: pwsh
        run: './WikiClientLibrary.Commons/CI/CollectArtifacts -Configuration ${{ matrix.config }}'
      - uses: actions/upload-artifact@master
        with:
          name: BuildArtifacts-${{ matrix.config }}
          path: ./CollectedArtifacts
